name: daily
on:
  push:
  schedule:
    - cron: "1 0 * * *"
jobs:
  Daily:
    working-directory: schedule
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - name: daily problem
        env:
          issueToken: ${{secrets.issueToken}}
        run: node daily-problem.js
      - name: daily check
        env:
          issueToken: ${{secrets.issueToken}}
        run: node daily-check.js
