name: daily
on:
  push:
  schedule:
    - cron: "1 0 * * *"

jobs:
  Daily:
    runs-on: ubuntu-latest
    steps:
      - name: daily problem and daily check
        env:
          issueToken: ${{secrets.issueToken}}
        run: npm run daily-schedule
