name: daily
on:
  push:
  schedule:
    - cron: "1 0 * * *"
defaults:
  run:
    working-directory: schedule

jobs:
  Daily:
    runs-on: ubuntu-latest
    steps:
      - name: daily problem
        env:
          issueToken: ${{secrets.issueToken}}
        run: node daily-problem.js
      - name: daily check
        env:
          issueToken: ${{secrets.issueToken}}
        run: node daily-check.js
